import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { SiteLocale } from './locales.ts'
import { docsRoot, messagesRoot, readJsonFile, registryPath, routesRoot } from './paths.ts'

export async function writeRegistry(locales: SiteLocale[]): Promise<void>
{
  const body = `/* eslint-disable */
// GENERATED by scripts/sync-content.ts - do not edit by hand.
// Add a locale by dropping i18n/messages/<code>.json (with "meta" section)
// and optional content/<code>/, then run npm run sync.
export interface SiteLocale {
  code: string
  prefix: \`/\${string}/\`
  label: string
  short: string
  navThird: 'adr' | 'config'
}

export const siteLocales: SiteLocale[] = ${JSON.stringify(locales, null, 2)}

export const defaultLocale: SiteLocale = siteLocales[0]
`
  await writeFile(registryPath, body)

  // Static JSON imports (generated import.meta.glob doesn't exist in the
  // vite.config.ts node context, and this keeps every consumer identical).
  // Locale codes are sanitized to valid identifiers (e.g. pt-BR → ptBR).
  const ident = (code: string): string => code.replaceAll(/[^A-Za-z0-9_$]/g, '')
  const messagesPath = join(docsRoot, 'src', 'lib', 'locale-messages.ts')
  const messagesBody = `/* eslint-disable */
// GENERATED by scripts/sync-content.ts — do not edit by hand.
${locales.map(l => `import ${ident(l.code)} from '../../i18n/messages/${l.code}.json'`).join('\n')}

export const localeMessages: Record<string, Record<string, Record<string, string>>> = {
${locales.map(l => `  '${l.code}': ${ident(l.code)},`).join('\n')}
}
`
  await writeFile(messagesPath, messagesBody)
}

export async function writeLandingWrapper(locale: SiteLocale): Promise<void>
{
  const dir = join(routesRoot, locale.code)
  const messages = (await readJsonFile(join(messagesRoot, `${locale.code}.json`), `locale messages for '${locale.code}'`)) as
  {
    landing?: { metaTitle?: string }
    label?: string
  }
  const title = messages.landing?.metaTitle ?? `AuthKit — ${locale.label}`
  await mkdir(dir, { recursive: true })
  await writeFile(
    join(dir, '+page.svelte'),
    `<script module>
  export const frontmatter = {
    title: ${JSON.stringify(title)},
    home: false,
    layout: false,
    header: false,
  }
</script>

<script>
  import Landing from '$lib/Landing.svelte'
</script>

<Landing base="${locale.prefix.slice(0, -1)}" />
`,
  )
  await writeFile(join(dir, '+page.js'), 'export const prerender = true\n')
}

// ADR section chrome: nested layout wrapping every /<locale>/adr/* page in
// .adr-page (see $lib/AdrChrome.svelte for the restyling). Generated because
// locale dirs are wiped on every sync.
export async function writeAdrLayout(locale: SiteLocale): Promise<void>
{
  const dir = join(routesRoot, locale.code, 'adr')
  await mkdir(dir, { recursive: true })
  await writeFile(
    join(dir, '+layout.svelte'),
    `<script>
  import AdrChrome from '$lib/AdrChrome.svelte'
  import { page } from '$app/state'

  let { children } = $props()
  const seg = $derived(page.url.pathname.split('/').filter(Boolean).pop() ?? '')
  const isIndex = $derived(seg === 'adr')
  const num = $derived(isIndex ? null : (seg.match(/^(\\d{3})/)?.[1] ?? null))
  const kicker = $derived(isIndex ? 'INDEX' : \`ADR-\${num ?? '···'}\`)
</script>

<div class="adr-page" class:adr-index={isIndex}>
  <AdrChrome {kicker} {num} />
  {@render children()}
</div>
`,
  )
}

// Section chrome: nested layout wrapping every /<locale>/<section>/* page
// in .doc-section (see $lib/SectionChrome.svelte). Generated because locale
// dirs are wiped on every sync.
export async function writeSectionLayout(locale: SiteLocale, section: string, label: string): Promise<void>
{
  const dir = join(routesRoot, locale.code, section)
  await mkdir(dir, { recursive: true })
  await writeFile(
    join(dir, '+layout.svelte'),
    `<script>
  import SectionChrome from '$lib/SectionChrome.svelte'
  import { page } from '$app/state'

  let { children } = $props()
  const seg = $derived(page.url.pathname.split('/').filter(Boolean).pop() ?? '')
</script>

<div class="doc-section">
  <SectionChrome name={seg} section="${label}" />
  {@render children()}
</div>
`,
  )
}
