/* eslint-disable */
// GENERATED by scripts/sync-content.ts — do not edit by hand.
import en from '../../i18n/messages/en.json'
import pl from '../../i18n/messages/pl.json'

export const localeMessages: Record<string, Record<string, Record<string, string>>> = {
  'en': en,
  'pl': pl,
}
